Feat/files s3 backend
Karmabunny/sprout3 pull request #124
Opened 2024-08-16 04:59 UTC by jamiemonksuk

**Reopening this to look at the implications and maybe reconsider**

Some things I want to tidy up:

- Migration tool (I'm changing it to allow a copy of files before the file system is swapped, otherwise dice will take days to migrate)
- File edit/save in admin (too slow, might need to ship some things off to workers)
- More testing and real world usage in dice
- Proper final review (needs a good sense check with a cleared head)

I've had to do a lot of work and make a few compromises to get the site to load in a reasonable amount of time when using s3 (or other remote back end). This includes things such as making local copies of files before working on them, splitting default resizing up into instant (for things admin will need when the page reloads) and worker based (for front end things like small, medium, etc.

I've also added heavy caching layers for things like filesize and imagesize which otherwise require pulling an entire file down to inspect.

I think this is working pretty well now.

**DB MIGRATION TOOL**

We need to be able to split up the migration, so we can copy large numbers of files without borking a site in between.
I've had a red hot go at this, by adding a tool to prepare / finalise / both at once.

This uses additional *migrated cols on the record. This will need a proper good test

![image](https://github.com/user-attachments/assets/c686f8a0-cb7f-4bac-970f-9eeb4c32e7b9)

![image](https://github.com/user-attachments/assets/c6697a3e-69bd-4028-a723-ac09ececb392)

![image](https://github.com/user-attachments/assets/0ca9573b-54ac-408e-8973-df2c10c8889c)

2024-12-14 04:16 UTC, jamiemonksuk commented
OK so this mega branch got out of control the first time around.

Then we left it for about 3 years, so the rebase was truly awful.

I've done a lot more work to update methods and optmise things.
I've spent a while testing imports, hot-swapping between local and s3, checking permissions etc

Seems to work well when set up as either private with signed URLs, or just a public bucket

I did a bunch of work towards automatically syncing buckets and permissions but it was getting a bit daft
- That can come later if need be...

2025-01-21 06:42 UTC, gwillz commented on src/sprout/Controllers/Admin/FileAdminController.php
> +                File::cleanupLocalCopy($src);
This should be wrapped in a `finally {}` block.

Perhaps something like:

```php
try {
  Pdb::update(...);
  $result = File::putExisting(...);

} catch (QueryException $e) {
  Json::error('Database error');

} catch (Throwable $e) {
  Kohana::logException($e, false);
  Json::error($e);

} finally {
  File::cleanupLocalCopy($temp_file);
  File::cleanupLocalCopy($src);
}
```

Few extra things:
- catching Throwable so error types don't sneak though
- exception caught = false - because it's not, just wrapped in JSON

2025-01-22 00:32 UTC, gwillz requested changes
A few things to address I think. Hard to summarise all of it.

I do think some of this needs to be addressed, particularly scrubbing exceptions `base64Thumb` - they need to go back in. A few typos and missing docs are easy enough to fix later.

I do worry about the S3 version of readfile and putStream. But that can also come later I guess. I wouldn't want to mess with that without having tests.

Happy to riff on some of these if you're short on time.

Overall I'm super excited by this. There's so much thought to making this work and work in the best way we can. Love the migration tool.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Controllers/Admin/FileAdminController.php
> +                Kohana::logException($e);
Same here for `caught = false` and catching Throwables. Don't wanna give the wrong impression in the log file.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Controllers/Admin/FileAdminController.php
> +            // File::deleteCache($original_filename);
Why not?

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Controllers/Admin/FileAdminController.php
> +        $res = FileTransform::resizeImage($temp_filename, $size, '', $focal_point_data);
Legit this already looks so much better.

Concise. Not wrapping other controllers. Not mangling `$_GET`. Not abusing transactions. So good.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/File.php
> +     * @return string|FilesBackend Depending if instanced or not
We can make this a `class-string<FilesBackend>|FilesBackend` for extra typing goodness.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/File.php
> +     * @deprecated. Use FileTransform::getTransformFilename
Tight, I was hoping you would do this.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/File.php
> +        $files = glob("files/resize/*/{$filename}");
Should this be `File::glob()` instead? Otherwise it's a relative glob in and disregards the backend.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/File.php
> +        $files = File::glob("cache/resize-*-{$filename}");
Are we moving the resize cache into the backend? Does this also mean these files are in `web/` ?

I feel like this change was meant for the `glob()` below.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/File.php
> +            'encoded_thumbnail' => Image::base64($file_path, $resize),
I hope you're right. I recall adding those ImageExceptions for a reason.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/FilesBackend.php
> +        $cache->set($key, $response, ['sprout-files'], $ttl);
Very nice. I suppose we should put some effort towards an Rdb driver for the cache interface.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/FilesBackend.php
> +        $functions = get_class_methods(__CLASS__);
Should use `static::class` here.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/FilesBackendS3.php
> +    }
Perhaps we can be more aggressive here and emit an exception. Just to really emphasise that, no, this method was a mistake and should never have existed publicly on the base abstract class.

Super aggressive would be to remove it entirely from the base class. Which is possibly safe considering we only added it ~14 months ago. I would doubt any active projects are using it. It only exists to make a single point for the `WEBROOT/files` path across the internals of the `FilesBackendDirectory`.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/FilesBackendS3.php
> +                echo $result['Body'];
This echo surprised me but of course it totally matches the interface for the builtin `readfile()`. Perhaps a comment would keep the next person from making a double take.

I did also check `readfile()` indeed prints to the output buffer as does echo. So no need for dodging any of that with `fwrite()`. Yay!

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/FilesBackendS3.php
> +        return $this->putString($filename, stream_get_contents($stream));
We haven't got anything better to stream the content to AWS?

Just if we have a large file this will blow the memory limit which defeats the purpose of using this streaming method at all.

I've used the AWS StreamWrapper before, which registers the `s3://` stream protocol and you can write chunks to it like a regular file.

Something like:

```php
$client->registerStreamsWrapper();
try {
  if ($target = fopen("s3://path/to/{$filename}", 'w')) {
   while (!feof($stream)) {
      fwrite($target, fread($stream, 100 * 1024));
    }
    fclose($target);
  }
} finally {
  stream_wrapper_unregister('s3');
}
```

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/FilesBackendS3.php
> +                echo $result['Body'];
Retro-thoughts from the notes about `putStream()`. What if the object is too big for the memory?

The `readfile()` has the advantage that it doesn't put the file into memory. So perhaps streaming the result here is also smart.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/WorkerFilesBackendMigrate.php
> +            ->all();
I dream of reworking all the helpers with this model. No more opaque arrays!

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Models/FileModel.php
> +        return $backend->absUrl($this->filename);
Very cool. I can see we're thinking about multi-instanced backends already. This is good.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/config/aws.php
> +// SHOULD NOT BE A ROOT USER - PLEASE USE IAM
:sweat_smile:

2025-01-22 00:32 UTC, gwillz commented on src/sprout/config/file.php
> +$config['backend_type'] = 's3';
This should default to local, no?

2025-01-22 00:32 UTC, gwillz commented on src/sprout/views/admin/file_edit.php
> +                        <img src="" alt="" id="manipulate-preview">
Was there a problem with rendering a placeholder image? Expensive API calls?

2025-01-22 00:32 UTC, gwillz commented on src/sprout/views/dbtools/file_backend_migrate.php
> +        and add migration type & date to te database.
typos + `&amp`

```and adds the migration type &amp date to the database.```

2025-01-22 00:32 UTC, gwillz commented on src/sprout/db_struct.xml
> +        <column name="imagesize" type="VARCHAR(1000)" />
I was going to suggest making this a TEXT to save column space and because we're never going to perform queries on this.

But we actually might - considering it's JSON data there's no reason we can't use JSON_EXTRACT and friends to find images of a certain size and whatever.

That all said often JSON is stored as TEXT anyway. So maybe that's still a good move.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/WorkerFilesBackendMigrate.php
> +        }
This whole worker might read better if it were broken in a method per action to contain the gritty details. Halfway there already.

- updateDatabaseRecords()
- prepareFileCopy()

Then this core method breaks down into just the high level decisions to see what does/doesn't happen.

(worker logs omitted)

```php
switch ($action) {
   case 'prepare':
      $this->prepareFileCopy();
      break;
   case 'update':
      $this->updateDatabaseRecords();
      break;
   case 'full':
      $this->prepareFileCopy();
      $this->updateDatabaseRecords();
      break;
   default:
      throw new InvalidArgumentException("Unknown action: {$action}");
}
```

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/WorkerFilesBackendMigrate.php
> +    private function getTransformName(string $filename)
Would this have any use outside of this worker? Could go into the FileTransform helper.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/views/dbtools/file_backend_migrate.php
> +    </p>
I love this 2-stage migration approach.

Only I'm never reassured that the old files are not deleted. Perhaps (and this is more work) there's a 3rd stage that cleans up the old files.

"Prepare" also doesn't sit right. Maybe just "Copy" is enough. It was a bit weird to read that in the worker and see it do copy actions, which didn't seem like preparation steps at first.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/FileTransform.php
> +    public static function createTransformSizes($filename_or_id, array $sizes, $specific_size = null, $file_backend_type = null)
Missing a @param doc for the `$sizes` array.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/FileTransform.php
> +            $img = new Image($temp_filename);
Could save effort (and unseen mistakes) here by wrapping the lot with try-finally.

```php
try {
   // everything, throws + returns
} finally {
  $file_backend->cleanupLocalCopy($tempfilename);
}
```

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/FileTransform.php
> +     * @throw Exception
This a good opportunity to use a specific exception type so consumers can differentiates between deeply thrown errors. For when this is inevitably wrapped 5 times over in some other helper.

We already have ImageException that might fit.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/FileTransform.php
> +     * @throws Exception
Same here about specific Exception types.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Controllers/FileController.php
> -                }
:star_struck: I've wanted this for so long.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/Aws/Aws.php
> +class Aws
Interesting approach to helpers for each AWS service. Pretty neat.

2025-01-22 00:32 UTC, gwillz commented on src/sprout/Helpers/Fb.php
> +                $view->orig_file = ['name' => 'Existing file', 'size' => File::size($temp_path)];
I bet it wasn't fun finding all of these.

2025-01-22 00:49 UTC, jamiemonksuk commented on src/sprout/Controllers/Admin/FileAdminController.php
> +                Kohana::logException($e);
That's fair, and on the other one

2025-01-22 00:50 UTC, jamiemonksuk commented on src/sprout/Controllers/Admin/FileAdminController.php
> +            // File::deleteCache($original_filename);
I suspect this was committed in error

2025-01-22 00:50 UTC, jamiemonksuk commented on src/sprout/Helpers/File.php
> +     * @return string|FilesBackend Depending if instanced or not
Nice thought!

2025-01-22 00:51 UTC, jamiemonksuk commented on src/sprout/Helpers/FileTransform.php
> +     * @throw Exception
Sounds like a job for... `FileTransformException` 

Honestly I'm all for exception specificity these days, and I'd prefer a folder with 30 classes in it, than trying to imply meaning from a message or code in a more generic error

2025-01-22 00:51 UTC, jamiemonksuk commented on src/sprout/Helpers/FileTransform.php
> +     * @throws Exception
I'm on board

2025-01-22 00:52 UTC, jamiemonksuk commented on src/sprout/Helpers/Fb.php
> +                $view->orig_file = ['name' => 'Existing file', 'size' => File::size($temp_path)];
Insert <tedious> gif here.

2025-01-22 00:59 UTC, jamiemonksuk commented on src/sprout/Helpers/File.php
> +        $files = glob("files/resize/*/{$filename}");
Yes it should. I had some gross merge conflicts around the glob changes for some reason

2025-01-22 01:00 UTC, jamiemonksuk commented on src/sprout/Helpers/File.php
> +            'encoded_thumbnail' => Image::base64($file_path, $resize),
It worked in all the tests I did on both back ends, I mucked with this one for a while originally. Crossing my fingers then...

2025-01-22 01:00 UTC, jamiemonksuk commented on src/sprout/Helpers/File.php
> +        $files = File::glob("cache/resize-*-{$filename}");
I think you're probably right here. I had some gross merge conflicts around the glob changes for some reason

2025-01-22 01:01 UTC, jamiemonksuk commented on src/sprout/Helpers/FilesBackend.php
> +        $cache->set($key, $response, ['sprout-files'], $ttl);
I would love that. I was gonna do it, but it was too much of a side project when this worked enough. Rdb would be way better at scale though

2025-01-22 01:01 UTC, jamiemonksuk commented on src/sprout/Helpers/FilesBackend.php
> +        $functions = get_class_methods(__CLASS__);
Yar

2025-01-22 01:02 UTC, jamiemonksuk commented on src/sprout/Helpers/FilesBackendS3.php
> +                echo $result['Body'];
That's a good point!

2025-01-22 01:06 UTC, jamiemonksuk commented on src/sprout/Helpers/FilesBackendS3.php
> +    }
I have used the baseDir method in a recent major media repository branch for another massive Sprout4 project we've been working on:

````php
    /**
     * Get the full system file path for a given filename
     *
     * @param string $filename
     * @return string
     */
    public function getFullPath(string $filename): string
    {
        return File::baseDir() . $this->prepareFilename($filename);
}
````

2025-01-22 01:07 UTC, jamiemonksuk commented on src/sprout/Helpers/FilesBackendS3.php
> +    }
Happy to be aggressive, but I'll need to rework and re-test that, as it's in QA Atm

2025-01-22 01:08 UTC, jamiemonksuk commented on src/sprout/Helpers/FilesBackendS3.php
> +        return $this->putString($filename, stream_get_contents($stream));
Ah yeah this looks like a better solution tbh

2025-01-22 01:08 UTC, jamiemonksuk commented on src/sprout/Helpers/WorkerFilesBackendMigrate.php
> +            ->all();
One day...

2025-01-22 01:09 UTC, jamiemonksuk commented on src/sprout/Models/FileModel.php
> +        return $backend->absUrl($this->filename);
Yeah, it should be well on the way to making it work

2025-01-22 01:09 UTC, jamiemonksuk commented on src/sprout/config/file.php
> +$config['backend_type'] = 's3';
Ah yeah I guess.. I suppose I only really had it like that for quickly testing on various local Sprout4 repos by symlinking it in

2025-01-22 01:10 UTC, jamiemonksuk commented on src/sprout/views/admin/file_edit.php
> +                        <img src="" alt="" id="manipulate-preview">
Yeah just slow, although I added a bunch of optimisations since then, so it might be OK to restore. Would need a quick test

2025-01-22 01:11 UTC, jamiemonksuk commented on src/sprout/views/dbtools/file_backend_migrate.php
> +        and add migration type & date to te database.
`&amp;` :D

But yeah, good spot!

2025-01-22 01:11 UTC, jamiemonksuk commented on src/sprout/Helpers/WorkerFilesBackendMigrate.php
> +        }
That would read better, agreed!

2025-01-22 01:12 UTC, jamiemonksuk commented on src/sprout/Helpers/WorkerFilesBackendMigrate.php
> +    private function getTransformName(string $filename)
I can see it being useful for sure. I'm always keen on having a good set of helpers on hand to... help

2025-01-22 01:13 UTC, jamiemonksuk commented on src/sprout/views/dbtools/file_backend_migrate.php
> +    </p>
Prepare would be clearer. I'd previously just been doing a prepare run, making sure it worked, then doing a full run.
Mostly I have been leaving the originals there because fear :D

2025-01-22 01:14 UTC, jamiemonksuk commented on src/sprout/Helpers/FileTransform.php
> +            $img = new Image($temp_filename);
Yeah good idea. There's a few good spots for a `finally` that you've picked up on

2025-01-22 22:39 UTC, gwillz commented on src/sprout/Helpers/FilesBackendS3.php
> +    }
Well that's interesting then. I guess leave it if we're doing stuff like that. 

The alternate is something like ```if (!$local) // has no path``` but we haven't got helpers like that yet.

2025-03-03 00:00 UTC, merged